const ColumnsPlanilha = [
  "Marca",
  "Categoria",
  "Acao",
  "Influenciador",
  "Plataforma",
  "Formato",
  "URL Publi",
  "Combo",
  "Quantidade",
  "Tipo De Entrega",
  "Tipo De Parceria",
  "Data de envio",
  "Hora de envio",
  "Apoio Count",
  "Seguidores",
  "Impressoes",
  "Visualizacoes",
  "Alcance",
  "Seguidores Alcancados",
  "Nao Seguidores",
  "Visualizacoes Completas",
  "Taxa de Retencao",
  "Tempo Medio de Visualizacao",
  "Taxa For You",
  "Cliques no Link",
  "Clique no @",
  "Clique na Hashtag",
  "Avancar",
  "Voltar",
  "Sair",
  "Proximo Story",
  "Visitas ao Perfil",
  "Comecaram a Seguir",
  "Tempo de Stories em Segundos",
  "Curtidas",
  "Salvamentos",
  "Compartilhamentos",
  "Comentarios/Respostas",
  "Data Publicacao",
  "Arquivos",
];

module.exports = ColumnsPlanilha;
